<a href="https://colab.research.google.com/github/zalish-shawon/py_notebooks/blob/main/Md_Zalish_Mahmud.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Email address: zalish.shawon@gmail.com

In [ ]:
import numpy as np
import pandas as pd

np.random.seed(42)

ids = np.arange(1, 11)
ages = np.random.randint(18, 60, 10)
salaries = np.random.randint(30000, 90000, 10)
departments = np.array(["HR", "IT", "Finance", "IT", "HR", "Sales", "Finance", "IT", "Sales", "HR"])

DF = pd.DataFrame({
"id": ids,
"age": ages,
"salary": salaries,
"dept": departments
})

DF.to_csv("employees.csv", index=False)
print("Sample Data Created and Saved as employees.csv")


Sample Data Created and Saved as employees.csv


### Answer to the Question no. 1

In [ ]:
ages_array = DF['age'].values
salaries_array = DF['salary'].values

print("Ages Array:")
print(ages_array)
print("Dtype:", ages_array.dtype)
print("Ndim:", ages_array.ndim)
print("Shape:", ages_array.shape)
print("Size:", ages_array.size)
print("\nSalaries Array:")
print(salaries_array)
print("Dtype:", salaries_array.dtype)
print("Ndim:", salaries_array.ndim)
print("Shape:", salaries_array.shape)
print("Size:", salaries_array.size)

Ages Array:
[56 46 32 25 38 56 36 40 28 28]
Dtype: int64
Ndim: 1
Shape: (10,)
Size: 10

Salaries Array:
[77191 74131 46023 71090 31685 30769 89735 86101 32433 35311]
Dtype: int64
Ndim: 1
Shape: (10,)
Size: 10


### Answer to the Question no. 2

In [ ]:
highest_salary = np.max(salaries_array)
lowest_salary = np.min(salaries_array)
average_salary = np.mean(salaries_array)
average_age = np.mean(ages_array)

print(f"Highest Salary: {highest_salary}")
print(f"Lowest Salary: {lowest_salary}")
print(f"Average Salary: {average_salary}")
print(f"Average Age: {average_age}")

Highest Salary: 89735
Lowest Salary: 30769
Average Salary: 57446.9
Average Age: 38.5


### Answer to the Question no. 3

In [ ]:
ages_greater_than_30 = ages_array[ages_array > 30]
print("Ages greater than 30:")
print(ages_greater_than_30)

count_greater_than_30 = len(ages_greater_than_30)
print(f"\nNumber of employees older than 30: {count_greater_than_30}")

Ages greater than 30:
[56 46 32 38 56 36 40]

Number of employees older than 30: 7


### Answer to the Question no. 4

In [ ]:
print(ages_array) #orginal array
updated_ages_array = ages_array + 5
print("Updated Ages Array:")
print(updated_ages_array)

[56 46 32 25 38 56 36 40 28 28]
Updated Ages Array:
[61 51 37 30 43 61 41 45 33 33]


### Answer to the Question no. 5

In [ ]:
total_salary_expense = np.sum(salaries_array)
salary_range = np.max(salaries_array) - np.min(salaries_array)

print(f"Total Salary Expense: {total_salary_expense}")
print(f"Difference between maximum and minimum salary: {salary_range}")

Total Salary Expense: 574469
Difference between maximum and minimum salary: 58966


### Answer to the Question no. 6

In [ ]:
employees_df = pd.read_csv('employees.csv')

print("First 5 rows of the DataFrame:")
display(employees_df.head())

print("\nBasic Info:")
employees_df.info()

print("\nSummary Statistics:")
display(employees_df.describe())

First 5 rows of the DataFrame:


id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR


Basic Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      10 non-null     int64 
 1   age     10 non-null     int64 
 2   salary  10 non-null     int64 
 3   dept    10 non-null     object
dtypes: int64(3), object(1)
memory usage: 452.0+ bytes

Summary Statistics:


id       age        salary
count  10.00000  10.00000     10.000000
mean    5.50000  38.50000  57446.900000
std     3.02765  11.16791  24357.262884
min     1.00000  25.00000  30769.000000
25%     3.25000  29.00000  33152.500000
50%     5.50000  37.00000  58556.500000
75%     7.75000  44.50000  76426.000000
max    10.00000  56.00000  89735.000000

### Answer to the Question no. 7

In [ ]:
print("DataFrame with only id, age, and salary columns:")
display(employees_df[['id', 'age', 'salary']])

print("\nLast 3 rows of the DataFrame:")
display(employees_df.tail(3))

DataFrame with only id, age, and salary columns:


id  age  salary
0   1   56   77191
1   2   46   74131
2   3   32   46023
3   4   25   71090
4   5   38   31685
5   6   56   30769
6   7   36   89735
7   8   40   86101
8   9   28   32433
9  10   28   35311


Last 3 rows of the DataFrame:


id  age  salary   dept
7   8   40   86101     IT
8   9   28   32433  Sales
9  10   28   35311     HR

### Answer to the Question no. 8

In [ ]:
it_employees = employees_df[employees_df['dept'] == 'IT']
print("Employees in the IT department:")
display(it_employees)

num_it_employees = len(it_employees)
print(f"\nTotal number of IT employees: {num_it_employees}")

Employees in the IT department:


id  age  salary dept
1   2   46   74131   IT
3   4   25   71090   IT
7   8   40   86101   IT


Total number of IT employees: 3


### Answer to the Question no. 9

In [ ]:
sorted_by_salary = employees_df.sort_values(by='salary', ascending=False)
top_3_employees = sorted_by_salary.head(3)

print("Top 3 highest-paid employees (including department and age):")
display(top_3_employees[['id', 'age', 'salary', 'dept']])

Top 3 highest-paid employees (including department and age):


id  age  salary     dept
6   7   36   89735  Finance
7   8   40   86101       IT
0   1   56   77191       HR

### Answer to the Question no. 10

In [ ]:
employees_df.loc[employees_df['salary'] > 80000, 'salary'] = 80000

new_average_salary = employees_df['salary'].mean()

print("DataFrame with updated salaries:")
display(employees_df)

print(f"\nNew average salary after replacement: {new_average_salary}")

DataFrame with updated salaries:


id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR
5   6   56   30769    Sales
6   7   36   80000  Finance
7   8   40   80000       IT
8   9   28   32433    Sales
9  10   28   35311       HR


New average salary after replacement: 55863.3
