<a href="https://colab.research.google.com/github/zalish-shawon/py_notebooks/blob/main/numPy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

arr1 = np.array(42)
arr2 = np.array([1,2,3,4,5])

arr3 = np.array([[2,23,44], [34,88,36]])

arr4 = np.array([[[2,23,44], [34,88,36], [89,100,102]]])


print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)
print(arr4.ndim)




0
1
2
3


### Higher Dimensional Arrays

In [2]:
arr = np.array([1,2,3,4,5], ndmin=5)

print(arr)

print("Number od Dimension: ",arr.ndim)

[[[[[1 2 3 4 5]]]]]
Number od Dimension:  5


### NumPy Array Indexing

In [3]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

arr2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr[0, 1])

print(arr2[1,-1])


[4 5 6]
10


## NumPy Array **Slicing**

In [4]:
arr = np.array([1,2,3,4,5,6,7])

print(arr[1:5])
print(arr[0:5])
print(arr[0:6])
print(arr[0:7])
print(arr[4:]) #Slice elements from index 4 to the end of the array
print(arr[:4])
print(arr[1:4:2])
print(arr[::2])

[2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5 6]
[1 2 3 4 5 6 7]
[5 6 7]
[1 2 3 4]
[2 4]
[1 3 5 7]


In [5]:
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

arr = np.array([1, 2, 3, 4], dtype="S")

print(arr)
print(arr.dtype)


int64
<U6
[b'1' b'2' b'3' b'4']
|S1


### NumPy Array Copy vs View

In [6]:
arr = np.array([1,2,3,4,5])

x = arr.copy()

arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [7]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]
